name: Compile to Javascript 

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if it's version commit
      id: check_commit
      run: |
        if [[ "${{ github.event.head_commit.message }}" == v* ]]; then
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "skip=false" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      if: env.skip == 'false'
      run: npm ci

    - name: Clean
      if: env.skip == 'false'
      run: npm run clean
    - name: Commit changes
      if: env.skip == 'false'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Compile to Javascript"
        git push